name: Weather Pipeline

on:
  schedule:
    - cron: '0 18 * * *'   # runs daily (approx 20:00 Denmark)
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install packages
        run: |
          pip install requests groq python-dotenv

      - name: Run script
        run: python fetch.py